# Generated by Django 5.0.4 on 2024-04-30 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='q5',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='q6',
        ),
        migrations.AddField(
            model_name='playlist',
            name='q1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q1', to='fitness.cancion'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='recharge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recharge', to='fitness.cancion'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='q2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q2', to='fitness.cancion'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='q3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q3', to='fitness.cancion'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='q4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q4', to='fitness.cancion'),
        ),
    ]
